version: '3.7'

services:
  web:
    build: .
    command: /diaryspace/run.sh
    volumes:
      - .:/diaryspace
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data: