# Compose image for testing.
# It is completely separate from your host file system, so all dependencies 
# such as node_modules and staticfiles are prepared automatically.

version: '3.7'

services:
  web:
    build: .
    command: /diaryspace/run.sh
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data:
